### ISSUE TITLE
mergeful-persistent-0.1.0.0 fails to build in ghc-9.4.3 Stackage Nightly

### ISSUE THREAD

**Issue by juhp** [NorfairKing/mergeful#4]
```
Building library for mergeful-persistent-0.1.0.0..                                                                      [237/196911]
[1 of 2] Compiling Data.Mergeful.Persistent                                                                                         
                                                                                                                                    
/var/stackage/work/unpack-dir/unpacked/mergeful-persistent-0.1.0.0-551e800e86e9f4bf879bda156c1e4af5ab29d451132ffb90459876e35f16b33a/
src/Data/Mergeful/Persistent.hs:258:9: error:        
    • Could not deduce (SafeToInsert record)              
        arising from a use of ‘insertMany_’                                                                                         
      from the context: (Ord sid, PersistField sid,            
                         ToBackendKey SqlBackend record, MonadIO m)           
        bound by the type signature for:                  
                   clientSyncProcessor :: forall record sid a (m :: * -> *).                                                        
                                          (Ord sid, PersistField sid,                                                               
                                           PersistEntityBackend record ~ SqlBackend,                                                
                                           ToBackendKey SqlBackend record, MonadIO m) =>                                            
                                          EntityField record (Maybe sid)
                                          -> EntityField record (Maybe ServerTime)                                                  
                                          -> EntityField record Bool                          
                                          -> EntityField record Bool                                                                
                                          -> (sid -> Timed a -> record)                                                             
                                          -> (record -> (sid, Timed a))                                                             
                                          -> (a -> [Update record])    
                                          -> ClientSyncProcessor (Key record) sid a (SqlPersistT m)                                 
        at src/Data/Mergeful/Persistent.hs:(174,1)-(199,56)
      Possible fix:                                               
        add (SafeToInsert record) to the context of
          the type signature for:                                 
            clientSyncProcessor :: forall record sid a (m :: * -> *).                                                               
                                   (Ord sid, PersistField sid,
                                    PersistEntityBackend record ~ SqlBackend,
                                    ToBackendKey SqlBackend record, MonadIO m) =>
                                   EntityField record (Maybe sid)
                                   -> EntityField record (Maybe ServerTime)
                                   -> EntityField record Bool
                                   -> EntityField record Bool
                                   -> (sid -> Timed a -> record)
                                   -> (record -> (sid, Timed a))
                                   -> (a -> [Update record])
                                   -> ClientSyncProcessor (Key record) sid a (SqlPersistT m)
    • In the first argument of ‘($)’, namely ‘insertMany_’
      In the expression:
        insertMany_ $ map (uncurry makeSyncedClientThing) (M.toList m)
      In an equation for ‘clientSyncProcessorSyncServerAdded’:
          clientSyncProcessorSyncServerAdded m                                                                          [195/196911]
            = insertMany_ $ map (uncurry makeSyncedClientThing) (M.toList m)
    |
258 |         insertMany_ $ map (uncurry makeSyncedClientThing) (M.toList m)
    |         ^^^^^^^^^^^

/var/stackage/work/unpack-dir/unpacked/mergeful-persistent-0.1.0.0-551e800e86e9f4bf879bda156c1e4af5ab29d451132ffb90459876e35f16b33a/
src/Data/Mergeful/Persistent.hs:290:5: error:
    • Could not deduce (SafeToInsert record)
        arising from a use of ‘insert_’
      from the context: (ToBackendKey SqlBackend record, MonadIO m)
        bound by the type signature for:
                   setupClientQuery :: forall record sid a (m :: * -> *).
                                       (PersistEntityBackend record ~ SqlBackend,
                                        ToBackendKey SqlBackend record, MonadIO m) =>
                                       (a -> record)
                                       -> (sid -> Timed a -> record)
                                       -> (sid -> Timed a -> record)
                                       -> (sid -> ServerTime -> record)
                                       -> ClientStore (Key record) sid a
                                       -> SqlPersistT m ()
        at src/Data/Mergeful/Persistent.hs:(274,1)-(285,18)
      Possible fix:
        add (SafeToInsert record) to the context of
          the type signature for: 
            setupClientQuery :: forall record sid a (m :: * -> *). 
                                (PersistEntityBackend record ~ SqlBackend,
                                 ToBackendKey SqlBackend record, MonadIO m) =>
                                (a -> record)
                                -> (sid -> Timed a -> record)
                                -> (sid -> Timed a -> record)
                                -> (sid -> ServerTime -> record)
                                -> ClientStore (Key record) sid a
                                -> SqlPersistT m ()
    • In the first argument of ‘($)’, namely ‘insert_’
      In the expression: insert_ $ makeSyncedClientThing sid tt
      In the second argument of ‘($)’, namely
        ‘\ (sid, tt) -> insert_ $ makeSyncedClientThing sid tt’
    |
290 |     insert_ $ makeSyncedClientThing sid tt
    |     ^^^^^^^
                                                                                                                        [154/196911]
/var/stackage/work/unpack-dir/unpacked/mergeful-persistent-0.1.0.0-551e800e86e9f4bf879bda156c1e4af5ab29d451132ffb90459876e35f16b33a/
src/Data/Mergeful/Persistent.hs:422:54: error:
    • Could not deduce (SafeToInsert record)
        arising from a use of ‘insert’
      from the context: (ToBackendKey SqlBackend record, MonadIO m)
        bound by the type signature for:
                   serverSyncProcessor :: forall cid record a (m :: * -> *).
                                          (PersistEntity record,
                                           PersistEntityBackend record ~ SqlBackend,
                                           ToBackendKey SqlBackend record, MonadIO m) =>
                                          EntityField record ServerTime
                                          -> [Filter record]
                                          -> (record -> Timed a)
                                          -> (cid -> a -> record)
                                          -> (a -> [Update record])
                                          -> ServerSyncProcessor cid (Key record) a (SqlPersistT m)
        at src/Data/Mergeful/Persistent.hs:(393,1)-(412,56)
      Possible fix:
        add (SafeToInsert record) to the context of
          the type signature for: 
            serverSyncProcessor :: forall cid record a (m :: * -> *).
                                   (PersistEntity record, PersistEntityBackend record ~ SqlBackend,
                                    ToBackendKey SqlBackend record, MonadIO m) =>
                                   EntityField record ServerTime
                                   -> [Filter record]
                                   -> (record -> Timed a)
                                   -> (cid -> a -> record)
                                   -> (a -> [Update record])
                                   -> ServerSyncProcessor cid (Key record) a (SqlPersistT m)
    • In the first argument of ‘($)’, namely ‘insert’
      In the second argument of ‘($)’, namely ‘insert $ makeFunc cid a’
      In the expression: fmap Just $ insert $ makeFunc cid a
    |
422 |       serverSyncProcessorAddItem cid a = fmap Just $ insert $ makeFunc cid a
    |                                                      ^^^^^^

/var/stackage/work/unpack-dir/unpacked/mergeful-persistent-0.1.0.0-551e800e86e9f4bf879bda156c1e4af5ab29d451132ffb90459876e35f16b33a/
src/Data/Mergeful/Persistent.hs:511:9: error:
    • Could not deduce (SafeToInsert record)
        arising from a use of ‘insert_’
      from the context: (Ord sid, PersistField sid,
                         ToBackendKey SqlBackend record, MonadIO m)                                                     [112/196911]
        bound by the type signature for:                                                                                            
                   serverSyncWithCustomIdProcessor :: forall cid sid record a
                                                             (m :: * -> *).
                                                      (Ord sid, PersistField sid,
                                                       PersistEntityBackend record ~ SqlBackend,
                                                       ToBackendKey SqlBackend record, MonadIO m) =>
                                                      EntityField record sid
                                                      -> SqlPersistT m sid
                                                      -> EntityField record ServerTime
                                                      -> [Filter record]
                                                      -> (record -> (sid, Timed a))
                                                      -> (cid -> sid -> a -> record)
                                                      -> (a -> [Update record])
                                                      -> ServerSyncProcessor
                                                           cid sid a (SqlPersistT m)
        at src/Data/Mergeful/Persistent.hs:(474,1)-(498,47)
      Possible fix:
        add (SafeToInsert record) to the context of
          the type signature for: 
            serverSyncWithCustomIdProcessor :: forall cid sid record a
                                                      (m :: * -> *).
                                               (Ord sid, PersistField sid,
                                                PersistEntityBackend record ~ SqlBackend,
                                                ToBackendKey SqlBackend record, MonadIO m) =>
                                               EntityField record sid
                                               -> SqlPersistT m sid
                                               -> EntityField record ServerTime
                                               -> [Filter record]
                                               -> (record -> (sid, Timed a))
                                               -> (cid -> sid -> a -> record)
                                               -> (a -> [Update record])
                                               -> ServerSyncProcessor cid sid a (SqlPersistT m)
    • In the first argument of ‘($)’, namely ‘insert_’
      In a stmt of a 'do' block: insert_ $ makeFunc cid uuid a
      In the expression:
        do uuid <- uuidGen
           insert_ $ makeFunc cid uuid a
           pure (Just uuid)
    |
511 |         insert_ $ makeFunc cid uuid a
    |         ^^^^^^^
```
