### ISSUE TITLE
fails to build with aeson-2.0

### ISSUE THREAD

**Issue by juhp** [NorfairKing/mergeful#2]
```
mergeful                       > /tmp/stack-ded59f11e665fc95/mergeful-0.2.0.0/src/Data/Mergeful/Collection.hs:188:7: error:
mergeful                       >     • Couldn't match type ‘Text’ with ‘Key’
mergeful                       >       Expected: [aeson-2.0.2.0:Data.Aeson.Types.Internal.Pair]
mergeful                       >         Actual: [(Text, Value)]
mergeful                       >     • In the second argument of ‘($)’, namely
mergeful                       >         ‘catMaybes
mergeful                       >            [jNull "added" clientStoreAddedItems,
mergeful                       >             jNull "synced" clientStoreSyncedItems,
mergeful                       >             jNull "changed" clientStoreSyncedButChangedItems,
mergeful                       >             jNull "deleted" clientStoreDeletedItems]’
mergeful                       >       In the expression:
mergeful                       >         object
mergeful                       >           $ catMaybes
mergeful                       >               [jNull "added" clientStoreAddedItems,
mergeful                       >                jNull "synced" clientStoreSyncedItems,
mergeful                       >                jNull "changed" clientStoreSyncedButChangedItems,
mergeful                       >                jNull "deleted" clientStoreDeletedItems]
mergeful                       >       In an equation for ‘toJSON’:
mergeful                       >           toJSON ClientStore {..}
mergeful                       >             = object
mergeful                       >                 $ catMaybes
mergeful                       >                     [jNull "added" clientStoreAddedItems,
mergeful                       >                      jNull "synced" clientStoreSyncedItems,
mergeful                       >                      jNull "changed" clientStoreSyncedButChangedItems, ....]
mergeful                       >     |
mergeful                       > 188 |       catMaybes
mergeful                       >     |       ^^^^^^^^^...
mergeful                       > 
mergeful                       > /tmp/stack-ded59f11e665fc95/mergeful-0.2.0.0/src/Data/Mergeful/Collection.hs:402:7: error:
mergeful                       >     • Couldn't match type ‘Text’ with ‘Key’
mergeful                       >       Expected: [aeson-2.0.2.0:Data.Aeson.Types.Internal.Pair]
mergeful                       >         Actual: [(Text, Value)]
mergeful                       >     • In the second argument of ‘($)’, namely
mergeful                       >         ‘catMaybes
mergeful                       >            [jNull "added" syncRequestNewItems,
mergeful                       >             jNull "synced" syncRequestKnownItems,
mergeful                       >             jNull "changed" syncRequestKnownButChangedItems,
mergeful                       >             jNull "deleted" syncRequestDeletedItems]’
mergeful                       >       In the expression:
mergeful                       >         object
mergeful                       >           $ catMaybes
mergeful                       >               [jNull "added" syncRequestNewItems,
mergeful                       >                jNull "synced" syncRequestKnownItems,
mergeful                       >                jNull "changed" syncRequestKnownButChangedItems,
mergeful                       >                jNull "deleted" syncRequestDeletedItems]
mergeful                       >       In an equation for ‘toJSON’:
mergeful                       >           toJSON SyncRequest {..}
mergeful                       >             = object
mergeful                       >                 $ catMaybes
mergeful                       >                     [jNull "added" syncRequestNewItems,
mergeful                       >                      jNull "synced" syncRequestKnownItems,
mergeful                       >                      jNull "changed" syncRequestKnownButChangedItems, ....]
mergeful                       >     |
mergeful                       > 402 |       catMaybes
mergeful                       >     |       ^^^^^^^^^...
mergeful                       > 
mergeful                       > /tmp/stack-ded59f11e665fc95/mergeful-0.2.0.0/src/Data/Mergeful/Collection.hs:527:7: error:
mergeful                       >     • Couldn't match type ‘Text’ with ‘Key’
mergeful                       >       Expected: [aeson-2.0.2.0:Data.Aeson.Types.Internal.Pair]
mergeful                       >         Actual: [(Text, Value)]
mergeful                       >     • In the second argument of ‘($)’, namely
mergeful                       >         ‘catMaybes
mergeful                       >            [jNull "client-added" syncResponseClientAdded,
mergeful                       >             jNull "client-changed" syncResponseClientChanged,
mergeful                       >             jNull "client-deleted" syncResponseClientDeleted,
mergeful                       >             jNull "server-added" syncResponseServerAdded, ....]’
mergeful                       >       In the expression:
mergeful                       >         object
mergeful                       >           $ catMaybes
mergeful                       >               [jNull "client-added" syncResponseClientAdded,
mergeful                       >                jNull "client-changed" syncResponseClientChanged,
mergeful                       >                jNull "client-deleted" syncResponseClientDeleted,
mergeful                       >                jNull "server-added" syncResponseServerAdded, ....]
mergeful                       >       In an equation for ‘toJSON’:
mergeful                       >           toJSON SyncResponse {..}
mergeful                       >             = object
mergeful                       >                 $ catMaybes
mergeful                       >                     [jNull "client-added" syncResponseClientAdded,
mergeful                       >                      jNull "client-changed" syncResponseClientChanged,
mergeful                       >                      jNull "client-deleted" syncResponseClientDeleted, ....]
mergeful                       >     |
mergeful                       > 527 |       catMaybes
mergeful                       >     |       ^^^^^^^^^...
mergeful                       > 
mergeful                       > /tmp/stack-ded59f11e665fc95/mergeful-0.2.0.0/src/Data/Mergeful/Collection.hs:560:17: error:
mergeful                       >     • Couldn't match expected type ‘Key’ with actual type ‘Text’
mergeful                       >     • In the first argument of ‘(.=)’, namely ‘n’
mergeful                       >       In the second argument of ‘($)’, namely ‘n .= s’
mergeful                       >       In the expression: Just $ n .= s
mergeful                       >     |
mergeful                       > 560 |     else Just $ n .= s
mergeful                       >     |                 ^
```

**Comment by NorfairKing** [comment]
Same here, do you have an `extra-deps` section to try this out with? 
I don't think I'll fix this until I need it though.
